name: wiki

on:
  push:
    branches:
      - master

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - run: |
        go run *.go --help         > wiki/Home.mediawiki
    - run: |
        cd wiki
        git config --global user.name  "actions-user"
        git config --global user.email "actions@github.com"
        git add . && git diff-index --quiet HEAD && exit 0
        git commit -m "Add changes" && git push
